### PR TITLE
Implemented mark procedures

### PR DESCRIPTION
**Pull request by Kirsten0604**
Made unit tests for ValueRib, Expressions, and Accumulator

### CODE REVIEW

**Comment by Kirsten0604** [comment]
Made unit tests for ValueRib, Expressions, and Accumulator

**Comment by bmwfire** [comment]
@btwooton Everything looks good on my end, however we may need to add an extra test case for each unit-test file to accommodate for rebinding functionality.

**Comment by CinchBlue** [comment]
Note: please make sure to:

```
git fetch upstream
git rebase upstream/master
```

We have been accepting changes into `master` a lot today from my team. Just FYI.

**Review by btwooton — APPROVED** [review]
Looks good to me. I am ready to merge, however you will notice that there is a warning pointing out the fact that this branch is far behind the base branch and should rebase prior to us commiting the merge. I will try to conduct the branch update on my end and then merge this PR. @Kirsten0604 once this PR is merged, please do the following on your local master branch.

`git pull --rebase upstream master`
`git push -f origin master`

Thanks for the PR, well done!

**Comment by btwooton** [comment]
@bmwfire As rebindings only effect the contents of the `Environment`, no additional unit tests are needed.

**Comment by btwooton** [comment]
All systems green. Squashing and merging into master. I will issue the PR with the final work on the GC later this evening.

**Pull request merged**
