### PR TITLE
Pull request GCList

### PR DESCRIPTION
**Pull request by bmwfire**
I have completed my tasks, GCList.cpp and unit-GCList.cpp. Please note that I also added two other methods to GCList.hpp, called is_empty() and get_size().

is_empty() checks the GCList and verifies whether or not it is empty.
get_size() simply allows access to the private size data.

In addition to those two added methods, this cpp file includes the constructor, destructor, add_data(GCData *data), and sweep() methods. Let me know if there are any questions or concerns.

### CODE REVIEW

**Review by btwooton — APPROVED** [review]
Looks good to me. Well done on the sweep() implementation. This implementation should suffice for our purposes for now, as we develop the initial prototype for the GC, and fine tune the interop with our current core system. The unit test confirms the functionality of the sweep() method. I approve this pull request. Well done Brandon.

**Comment by bmwfire** [comment]
Ok excellent. I'm noticing that GitHub is giving me an error check for my final commit. Should I be concerned of this?

**Comment by btwooton** [comment]
@bmwfire The error in the travis-ci build is due to a broken unit test in the `MacroContext` code. The build will not pass until this unit test is fixed by @VermillionAzure. I have added him as a reviewer as I believe he is the only one able to merge your PR despite the failing build. All of your unit tests are passing, so don't worry about it.

**Comment by CinchBlue** [comment]
I'm on duty now. I will fix the unit test now.

**Comment by CinchBlue** [comment]
I have finished a pull request to fix the `MacroContextChecker` unit test case in order to solve the error that is stopping this from merging. Thus, I am blocking you until the pull request is finished (it shouldn't take long, whoever wants to review it). Sorry for the inconvenience 🙁 

https://github.com/uhmanoa-transpiler-project/shaka-scheme/pull/57

**Comment by bmwfire** [comment]
I'm reviewing it now. @VermillionAzure

**Comment by bmwfire** [comment]
@VermillionAzure There seems to be new errors despite your changes.

**Comment by btwooton** [comment]
The build failed at apt-get install gcc-6

**Comment by bmwfire** [comment]
Yes I saw that. How do we fix it?

**Comment by CinchBlue** [comment]
Just had to rerun the build. It appears to be passing now.

**Comment by CinchBlue** [comment]
Since Troy already reviewed this, I will squash and merge the changes into `master`. Good job @bmwfire !

**Pull request merged**
